server:
  port: 8081

spring:
  application:
    name: "oauth2"

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: "924069675528889"
            client-secret: "474258525dbf63343dd443c99b32c840"

          google:
            client-id: "384814260447-6mcor02lje7qaf7k8i8tri6jn5n1tgt6.apps.googleusercontent.com"
            client-secret: "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"

          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID} # 96d45143d67b5449cb81a098cc354c6d
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET} # W41QQl3dORFdBSNUyR46No2boTwPWiZn
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST


        provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id

